/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

import org.example.item.Item;

public class App {
    public String getGreeting() {
        return "Hello Second World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Item item = new Item();
        List<String> list = new ArrayList<String>();
    }
}
