name: TEST & CI
on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10      # SpotBugs 추가로 시간 여유
    permissions:
      checks: write
      pull-requests: write
      security-events: write # SARIF 업로드용

    
    defaults:
      run:
        shell: bash
        working-directory: ./practice-gradle
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          java-version: '21'              # JDK21로 통일 (필요 시 17 유지)
          distribution: 'temurin'

      - name: Grant Gradle exec permission
        run: chmod +x gradlew

      # ---------- QUALITY GATE ----------
      - name: Spotless Check
        id: spotless
        run: ./gradlew spotlessCheck

      - name: Spotless Fix Suggestion
        if: failure() && steps.spotless.outcome == 'failure'
        uses: reviewdog/action-suggester@v1.5.1
        with:
          tool_name: spotless
          github_token: ${{ secrets.ACTION_TOKEN }}

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain
        continue-on-error: true 

      - name: Upload SpotBugs SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: practice-gradle/app/build/reports/spotbugs/main.sarif

      - name: Run Unit Tests
        run: ./gradlew test -Dspring.profiles.active=test

      - name: Publish Unit-Test Summary
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: practice-gradle/app/build/test-results/test/TEST-*.xml

      - name: Coverage Report (JaCoCo)
        id: jacoco
        uses: madrapps/jacoco-report@v1.6
        with:
          title: Test Coverage Report
          token: ${{ secrets.ACTION_TOKEN }}
          paths: ${{ github.workspace }}/practice-gradle/app/build/reports/jacoco/test/jacocoTestReport.xml
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          
